algoritmo "multi_2_inte"
// Função :
// Autor : Guilherme
// Data : 15/08/2018
// Seção de Declarações 
var
   num1 : inteiro
   num2 : inteiro
   res : inteiro

inicio
      //entrada
      escreval ("Digite o número 1:")
      leia (num1)
      escreval ("Digite o número 2:")
      leia (num2)
      
      //processamento
      res <- num1 * num2
      
      //saida
      limpatela
      escreval (num1, " multiplicado por", num2, " é igual a", res)
      
      
fimalgoritmo
