algoritmo "soma_3_int"
// Função :
// Autor : guilherme
// Data : 15/08/2018
// Seção de Declarações 
var
   num1 : inteiro
   num2 : inteiro
   num3 : inteiro
   res : inteiro
inicio
      // entrada
      escreval ("Digite o número 1:")
      leia (num1)
      escreval ("Digite o número 2:")
      leia (num2)
      escreval ("Digite o número 3:")
      leia (num3)

      //processamento
      res <- num1 + num2 + num3
      
      //saida
      escreval ("Resultado: ", res)
fimalgoritmo
